name: dynamic_forms
description: Dart library providing infrastructure to parse complex external form with expressions into a custom model.
version: 0.14.0
homepage: https://github.com/OndrejKunc/flutter_dynamic_forms

environment:
  sdk: '>=2.12.0-259.8.beta <3.0.0'

dependencies:
  xml: ^5.0.0-nullsafety
  rxdart: ^0.26.0-nullsafety

  expression_language:
    path: ../expression_language
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  test: ^1.16.0-nullsafety
  pedantic: ^1.10.0-nullsafety
