name: flutter_dynamic_forms_components
description: Flutter package containing default set of dynamic form components.
version: 1.0.0
homepage: https://github.com/OndrejKunc/flutter_dynamic_forms

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  intl: ^0.17.0

  flutter_dynamic_forms: 
    path: ../flutter_dynamic_forms

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.0
  pedantic: ^1.8.0+1
  dynamic_forms_generator:
    path: ../dynamic_forms_generator

flutter:
